### ISSUE TITLE
Jupyter-Lab Gui Glitch

### ISSUE THREAD

**Issue by apaeffgen** [transentis/bptk_py#23]
System-Specs:
Using bptk_py in Jupyter-Lab (https://jupyter.org/) on MacOS 13.6.7 (22G720). Python Python 3.12.4, bptk_py 1.9.0.

Glitch: Compiling the Notebook brings up an error, that is not relevant for the calculation. See screenshot also Screenshot:

Quote:
```
from BPTK_Py import Model
from BPTK_Py import sd_functions as sd
model = Model(starttime=1.0, stoptime=10.0, dt=1.0,name='Emotion')
<unknown>:1: SyntaxWarning: invalid escape sequence '\w'
<unknown>:1: SyntaxWarning: i
```
End Quote:

For printing, exporting...., this is confusing for other users. A second compile kills the message, but brings up a new sequence of cells. See second screenshot.

Any ideas how to fix it? 
Python and jupyter are installed with brew. All other functions of the installed software work as expected.

![Bildschirmphoto-Modell_Intra… (2) - JupyterLab - Jupyter 2024-07-19 18-56-20](https://github.com/user-attachments/assets/1250130a-8205-41f8-b06c-3ed24c83a134)
![Bildschirmphoto-Modell_Intra… (2) - JupyterLab - Jupyter 2024-07-19 18-57-00](https://github.com/user-attachments/assets/a6703de8-5b4c-4e3a-8065-8366b12cd713)

**Comment by olivergrasl** [comment]
> System-Specs:
> 
> Using bptk_py in Jupyter-Lab (https://jupyter.org/) on MacOS 13.6.7 (22G720). Python Python 3.12.4, bptk_py 1.9.0.
> 
> 
> 
> Glitch: Compiling the Notebook brings up an error, that is not relevant for the calculation. See screenshot also Screenshot:
> 
> 
> 
> Quote:
> 
> ```
> 
> from BPTK_Py import Model
> 
> from BPTK_Py import sd_functions as sd
> 
> model = Model(starttime=1.0, stoptime=10.0, dt=1.0,name='Emotion')
> 
> <unknown>:1: SyntaxWarning: invalid escape sequence '\w'
> 
> <unknown>:1: SyntaxWarning: i
> 
> ```
> 
> End Quote:
> 
> 
> 
> For printing, exporting...., this is confusing for other users. A second compile kills the message, but brings up a new sequence of cells. See second screenshot.
> 
> 
> 
> Any ideas how to fix it? 
> 
> Python and jupyter are installed with brew. All other functions of the installed software work as expected.
> 
> 
> 
> ![Bildschirmphoto-Modell_Intra… (2) - JupyterLab - Jupyter 2024-07-19 18-56-20](https://github.com/user-attachments/assets/1250130a-8205-41f8-b06c-3ed24c83a134)
> 
> ![Bildschirmphoto-Modell_Intra… (2) - JupyterLab - Jupyter 2024-07-19 18-57-00](https://github.com/user-attachments/assets/a6703de8-5b4c-4e3a-8065-8366b12cd713)
> 
> 

it's been annoying me to and we've been a bit lax about updates recently ... we'll get it fixed at the beginning of next week

**Comment by olivergrasl** [comment]
this should be fixed now
